version: '3.4'

services:
  postgres: 
    image: postgres
    shm_size: 14gb
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      
   #volumes:
   #  postgres:
   #    driver: local


  #pointofsalemicroservices.bootstrapper:
  #  image: ${DOCKER_REGISTRY-}pointofsalemicroservicesbootstrapper
  #  build:
  #    context: .
  #    dockerfile: Bootstrapper/PointOfSaleMicroservices.Bootstrapper/Dockerfile
